#!/bin/bash
cd /
set -euo pipefail

PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/linhancheng/.local/bin"
export PATH

REPO_DIR="/Users/linhancheng/code/social-info"
OUT_DIR="$REPO_DIR/reports/local-analysis"
LOG_DIR="$REPO_DIR/logs"
PROJECTS_DIR="/Users/linhancheng/.claude/projects"

mkdir -p "$OUT_DIR" "$LOG_DIR"
DATE="${LOCAL_ANALYSIS_DATE:-$(date +%Y-%m-%d)}"
OUT="$OUT_DIR/$DATE-codex-violation.md"
LOG="$LOG_DIR/local-analysis-codex-violation-$DATE.log"

{
  echo "=== codex-violation weekly started: $(date) ==="

  TMP_SESSIONS=$(mktemp)
  CANDIDATES=$(mktemp)
  trap 'rc=$?; rm -f "$TMP_SESSIONS" "$CANDIDATES"; exit $rc' EXIT

  find "$PROJECTS_DIR" -name "*.jsonl" -mtime -7 -type f 2>/dev/null > "$TMP_SESSIONS"
  TOTAL_SESSIONS=$(wc -l < "$TMP_SESSIONS" | tr -d ' ')

  while IFS= read -r f; do
    SESSION=$(basename "$f" .jsonl)
    PROJECT=$(basename "$(dirname "$f")")

    HAS_CODEX=$(grep -cE 'codex' "$f" 2>/dev/null) || HAS_CODEX=0
    [ "$HAS_CODEX" -eq 0 ] && continue

    BASH_SLEEP=$(grep -cE '"name":"Bash"[^}]*sleep [0-9]' "$f" 2>/dev/null) || BASH_SLEEP=0
    [ "$BASH_SLEEP" -eq 0 ] && continue

    BASH_SLEEP_CODEX=$(grep -cE '"name":"Bash"[^}]*sleep [0-9][^}]*codex' "$f" 2>/dev/null) || BASH_SLEEP_CODEX=0
    BASH_CODEX_SLEEP=$(grep -cE '"name":"Bash"[^}]*codex[^}]*sleep [0-9]' "$f" 2>/dev/null) || BASH_CODEX_SLEEP=0
    BASH_SLEEP_CODEX_FILE=$(grep -cE '"name":"Bash"[^}]*sleep [0-9][^}]*(/\.codex/|/tmp/codex-|rollout-)' "$f" 2>/dev/null) || BASH_SLEEP_CODEX_FILE=0

    COOCCUR=$((BASH_SLEEP_CODEX + BASH_CODEX_SLEEP + BASH_SLEEP_CODEX_FILE))
    [ "$COOCCUR" -eq 0 ] && continue

    MTIME=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M" "$f")
    echo "$COOCCUR|$SESSION|$PROJECT|$MTIME|$f" >> "$CANDIDATES"
  done < "$TMP_SESSIONS"

  HIT_COUNT=$(wc -l < "$CANDIDATES" | tr -d ' ')

  {
    echo "# Codex 違反 Weekly Report — $DATE"
    echo ""
    echo "**掃描範圍**：過去 7 天 mtime 內、$TOTAL_SESSIONS session jsonl"
    echo "**Candidate Filter**：jsonl 內含 \`\"name\":\"Bash\"\` tool_use + 同 message 內 sleep + codex cooccur"
    echo "**規則來源**：\`~/.claude/references/codex-rescue.md\`（2026-07-19 更新版）——短 job 前景 task --fresh；長 job（>8-10 min）前景撞 CC Bash 600000ms 硬 clamp、**合法路徑 = nohup detach + rollout jsonl poll**（pr-review.md canonical）。違規樣態只剩「naive run_in_background 直包 companion + sleep 輪詢已斷的 stdout」"
    echo "**注意**：此 report 是 candidate list、非判定違反；user 進 session 看上下文後自行判定真違反 / 合法 sleep。已知合法樣態（07-19 判例 5/5）：pr-review by-design background+poll / codex CLI 行為觀察等 rollout 落檔 / 輪詢自己的 CC 背景任務 / kill-wait"
    echo ""
    echo "---"
    echo ""
    echo "## 命中 $HIT_COUNT session"
    echo ""

    if [ "$HIT_COUNT" -eq 0 ]; then
      echo "✅ 過去 7 天無 codex+sleep Bash cooccur session。"
      echo ""
      echo "Review action: 無需動作。"
    else
      echo "按 Bash sleep+codex cooccur 次數 desc 排序："
      echo ""
      echo "| # | Session | Project | Mtime | Cooccur |"
      echo "|---|---|---|---|---|"

      sort -t'|' -k1 -n -r "$CANDIDATES" | awk -F'|' -v OFS='|' '{
        idx++
        print idx, $2, $3, $4, $1
      }' | while IFS='|' read -r idx sess proj mtime cooccur; do
        echo "| $idx | \`$sess\` | \`$proj\` | $mtime | $cooccur |"
      done
      echo ""

      echo "## Review Action"
      echo ""
      echo "1. 對每個 session 用 \`claude --resume <session-id>\` 或直接 cat jsonl 找 Bash tool_use 含 sleep 的命令、看前後 context 判定"
      echo "2. 真違反 ≥ 1 條 → 考慮 patch \`~/.claude/rules/common/codex-rescue.md\` 加新「具體違反 example」段"
      echo "3. 連續 N 週 ≥ 5 session → 重啟 T6 hook 評估（見 \`docs/superpowers/specs/2026-06-21-T6-tool-misuse-pattern-detector-design.md\` DEFERRED 段 trigger）"
      echo ""

      echo "## Quick jsonl inspect"
      echo ""
      echo "對任一 session 抽 Bash sleep+codex 命令："
      echo '```bash'
      echo 'jq -c '"'"'select(.message.content[]?.type == "tool_use" and .message.content[].name == "Bash" and (.message.content[].input.command // "" | test("sleep [0-9].*(codex|codex-companion)|codex.*sleep [0-9]")))'"'"' <jsonl>'
      echo '```'
    fi

    echo ""
    echo "_Generated by codex-violation-weekly.sh_"
  } > "$OUT"

  echo "=== codex-violation weekly finished: $(date) ==="
  echo "Output: $OUT ($(wc -c < "$OUT") bytes, $HIT_COUNT session hits)"
} >> "$LOG" 2>&1
