#!/bin/bash
cd /
set -euo pipefail

PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/linhancheng/.local/bin"
export PATH

REPO_DIR="/Users/linhancheng/code/social-info"
OUT_DIR="$REPO_DIR/reports/local-analysis"
LOG_DIR="$REPO_DIR/logs"
PROJECTS_DIR="/Users/linhancheng/.claude/projects"

mkdir -p "$OUT_DIR" "$LOG_DIR"
DATE=$(date +%Y-%m-%d)
OUT="$OUT_DIR/$DATE-verify-mismatch.md"
LOG="$LOG_DIR/local-analysis-verify-mismatch-$DATE.log"

{
  echo "=== verify-mismatch weekly started: $(date) ==="

  TMP_SESSIONS=$(mktemp)
  CANDIDATES=$(mktemp)
  trap 'rm -f "$TMP_SESSIONS" "$CANDIDATES"' EXIT

  find "$PROJECTS_DIR" -name "*.jsonl" -mtime -7 -type f 2>/dev/null > "$TMP_SESSIONS"
  TOTAL_SESSIONS=$(wc -l < "$TMP_SESSIONS" | tr -d ' ')

  while IFS= read -r f; do
    SESSION=$(basename "$f" .jsonl)
    PROJECT=$(basename "$(dirname "$f")")

    # 只看 assistant text message（過濾 user / tool_result / tool_use noise）
    # E1: turn 含 verify 段標記詞
    HAS_VERIFY_HDR=$(grep -cE '"text":"[^"]*(驗證對照|驗證證據|逐項驗證|對照驗證|expected.*actual|Verify against expectation)' "$f" 2>/dev/null) || HAS_VERIFY_HDR=0

    # E2: turn 含「預期 X / 實際 Y」結構詞
    HAS_EXPECT_ACTUAL=$(grep -cE '"text":"[^"]*預期[^"]*實際' "$f" 2>/dev/null) || HAS_EXPECT_ACTUAL=0

    # E3: turn 含 ✅ + match / 匹配 string
    HAS_MATCH_TAG=$(grep -cE '"text":"[^"]*(✅[^"]*match|✅[^"]*匹配|✅ 全[ 對]|✅ 全 match|all match)' "$f" 2>/dev/null) || HAS_MATCH_TAG=0

    TOTAL=$((HAS_VERIFY_HDR + HAS_EXPECT_ACTUAL + HAS_MATCH_TAG))
    [ "$TOTAL" -eq 0 ] && continue

    MTIME=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M" "$f")
    echo "$TOTAL|$SESSION|$PROJECT|$MTIME|$f|$HAS_VERIFY_HDR|$HAS_EXPECT_ACTUAL|$HAS_MATCH_TAG" >> "$CANDIDATES"
  done < "$TMP_SESSIONS"

  HIT_COUNT=$(wc -l < "$CANDIDATES" | tr -d ' ')

  {
    echo "# Verify-mismatch Weekly Report — $DATE"
    echo ""
    echo "**掃描範圍**：過去 7 天 mtime 內、$TOTAL_SESSIONS session jsonl"
    echo "**Candidate Filter**：assistant text 內含三類 verify-段標記詞之一："
    echo "  - E1 段標記：\`驗證對照 / 驗證證據 / 逐項驗證 / 對照驗證 / expected.*actual\`"
    echo "  - E2 X/Y 結構：\`預期...實際\`"
    echo "  - E3 蓋章詞：\`✅ match / ✅ 匹配 / ✅ 全 / all match\`"
    echo "**目的**：抽出 CC 寫 verify 對照表的 turn、user 抽查 CC 是不是在敷衍蓋 ✅"
    echo "**注意**：此 report 是 candidate list、非自動判定 mismatch；user 進 session 看 X/Y 是否真對得上"
    echo ""
    echo "---"
    echo ""
    echo "## 命中 $HIT_COUNT session"
    echo ""

    if [ "$HIT_COUNT" -eq 0 ]; then
      echo "✅ 過去 7 天無 verify 表 candidate。"
      echo ""
      echo "Review action: 無需動作。"
    else
      echo "按 verify 標記總命中數 desc 排序："
      echo ""
      echo "| # | Session | Project | Mtime | 段標記 | X/Y 結構 | 蓋章詞 | 總 |"
      echo "|---|---|---|---|---|---|---|---|"

      sort -t'|' -k1 -n -r "$CANDIDATES" | awk -F'|' -v OFS='|' '{
        idx++
        print idx, $2, $3, $4, $6, $7, $8, $1
      }' | while IFS='|' read -r idx sess proj mtime hdr ea match total; do
        echo "| $idx | \`$sess\` | \`$proj\` | $mtime | $hdr | $ea | $match | $total |"
      done
      echo ""

      echo "## Review Action"
      echo ""
      echo "1. 對 top N session 用 \`claude --resume <session-id>\` 或 cat jsonl 找 verify 段"
      echo "2. 對每個 verify 段問三個問題："
      echo "   - X (預期) 是否具體可觀察、不是「全測試綠」這種寬泛字眼"
      echo "   - Y (實際) 是否附獨立可 verify 證據（output / file path + line / commit hash）、不是 self-description"
      echo "   - ✅ 標記是否真的 X/Y 字眼結構對齊（而非自說自話）"
      echo "3. 發現 CC 真敷衍 → 跟 CC 講「row N 的 ✅ 蓋得太爽、X 太抽象 / Y 沒附獨立 trace」、推 CC 重 verify"
      echo "4. 連續多週 ≥ 50 candidate → 考慮重啟 T4 hook 評估（spec 在 STATE.md T4 row）"
      echo ""

      echo "## Quick jsonl inspect"
      echo ""
      echo "對任一 session 抽 verify 段 assistant text："
      echo '```bash'
      echo "jq -c 'select(.type == \"assistant\" and (.message.content[]?.text // \"\" | test(\"預期.*實際|驗證對照|✅.*match\"))) | .message.content[].text // empty' <jsonl> | head -20"
      echo '```'
    fi

    echo ""
    echo "_Generated by verify-mismatch-weekly.sh_"
  } > "$OUT"

  echo "=== verify-mismatch weekly finished: $(date) ==="
  echo "Output: $OUT ($(wc -c < "$OUT") bytes, $HIT_COUNT session hits)"
} >> "$LOG" 2>&1
